title = "/home/mufeed"
base_url = "https://mufeed.dev"
theme = "cat"
compile_sass = true
minify_html = true
build_search_index = false
author = "Mufeed Ali"

[markdown]
lazy_async_image = true
render_emoji = true

[extra.externals]
github = "https://github.com/mufeedali"
mastodon = "https://social.odka.org/@mufeedali"
linkedin = "https://linkedin.com/in/mufeed-ali-7988121b9"
email = "mailto:me@mufeed.dev"

[extra]
externals_order = ["github", "mastodon", "linkedin", "email"]
menu = [
    { name = "Projects", url = "/projects", weight = 1 },
    { name = "Blog", url = "/blog", weight = 2 },
]
